// <auto-generated>
// Rewired Constants
// This list was generated on 5/29/2018 8:10:42 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P1_MoveHorizontal")]
        public const int P1_MoveHorizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P1_MoveVertical")]
        public const int P1_MoveVertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P1_Attack")]
        public const int P1_Attack = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P1_Defense")]
        public const int P1_Defense = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P2_MoveHorizontal")]
        public const int P2_MoveHorizontal = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P2_MoveVertical")]
        public const int P2_MoveVertical = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P2_Attack")]
        public const int P2_Attack = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "P2_Defense")]
        public const int P2_Defense = 11;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int Category0 = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int Layout0 = 1;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
}
